# Generated by Django 5.0.6 on 2024-05-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family',
            new_name='SubCategory',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_delivered',
            new_name='is_closed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='odered_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='family',
            new_name='subcategory',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
