# Generated by Django 4.2 on 2024-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('dispatched', 'Expédiée'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=50),
        ),
    ]
