# Generated by Django 4.2 on 2024-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='../static/imgs/logo-g.png', null=True, upload_to='store/categories/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='../static/imgs/logo-g.png', upload_to='store/products/images/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default='../static/imgs/logo-g.png', null=True, upload_to='store/subcategories/'),
        ),
    ]
