# Generated by Django 4.2 on 2024-08-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_type',
            new_name='type',
        ),
    ]
