# Generated by Django 4.2 on 2024-08-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_delivery_type_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='../static/imgs/logo-g.png', upload_to='store/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='../static/imgs/logo-g.png', upload_to='store/products/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='../static/imgs/logo-g.png', upload_to='store/subcategories/'),
        ),
    ]
