# Generated by Django 4.2 on 2024-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_amount_order_items_shippinginfo_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=97998621, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processed', 'En cours'), ('delivered', 'Livrée')], default='pending', max_length=50),
        ),
    ]
