# Generated by Django 5.0.6 on 2024-05-28 14:45

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_phone_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_closed',
            new_name='is_cancelled',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processed', 'Traitée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('amount_due', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('ongoing', 'En cours'), ('finished', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=50)),
                ('is_vip', models.BooleanField(default=False)),
                ('d_day', models.DateField(default=utils.get_tomorrow)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('observation', models.CharField(blank=True, max_length=500, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/deliveries/')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
    ]
