# Generated by Django 4.2 on 2024-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_image_alter_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/static/imgs/logo-g.png', upload_to='store/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='/static/imgs/logo-g.png', upload_to='store/products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='/static/imgs/logo-g.png', upload_to='store/products/images/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='/static/imgs/logo-g.png', upload_to='store/subcategories/'),
        ),
    ]
