# Generated by Django 4.2 on 2024-08-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('products', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('note', models.CharField(choices=[('excellent', 'Excellent'), ('very-good', 'Très bon'), ('good', 'Bon'), ('mid', 'Moyen'), ('bad', 'Mauvais')], default='good', max_length=50)),
                ('comment', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
