# Generated by Django 4.2 on 2024-08-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeedback',
            name='order',
        ),
    ]
