# Generated by Django 4.2 on 2024-06-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_is_favorite_product_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=1000)),
                ('eta', models.IntegerField(default=3)),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('dispatched', 'Expédiée'), ('finished', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=50),
        ),
    ]
