# Generated by Django 4.2 on 2024-08-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_productfeedback_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeedback',
            name='note',
            field=models.CharField(choices=[(5, 'Excellent'), (4, 'Très bon'), (3, 'Bon'), (2, 'Moyen'), (1, 'Mauvais')], default='good', max_length=50),
        ),
    ]
