# Generated by Django 4.2 on 2024-08-29 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_productfeedback_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFeedback',
        ),
    ]
