# Generated by Django 4.2 on 2024-08-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_image_product_main_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='thumbnail',
        ),
    ]
