version: '3'

services:
  django:
    build: .
    command: sh -c "daphne -b 0.0.0.0 -p 8000 dermepro.asgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

# NGINX setup----------------------------------------------------------------------
# version: '3'

# services:
#   django:
#     build: .
#     command: sh -c "daphne -b 0.0.0.0 -p 8000 myproject.asgi:application"
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/sites-available/default
#     depends_on:
#       - django
