# Generated by Django 4.2 on 2024-05-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliveryinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryInfo',
        ),
    ]
