# Generated by Django 4.2 on 2024-08-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_deliveryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_cart',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
