# Generated by Django 5.0.6 on 2024-05-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('store', '0007_rename_user_order_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('catch_phrase', models.TextField(default='')),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/blogposts/')),
                ('products', models.ManyToManyField(blank=True, to='store.product')),
            ],
        ),
    ]
