# Generated by Django 4.2 on 2024-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('catch_phrase', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/home_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
