# Generated by Django 5.0.6 on 2024-05-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_promotion'),
        ('store', '0008_remove_product_slug_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='store.product'),
        ),
    ]
