# Generated by Django 4.2 on 2024-08-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_homeimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/home_images/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(default='../static/imgs/blog.png', upload_to='store/blogposts/'),
        ),
    ]
