# Generated by Django 4.2 on 2024-08-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_homeimages_image_alter_promotion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='../static/imgs/blog.png', upload_to='store/blogposts/'),
        ),
    ]
