# Generated by Django 4.2 on 2024-08-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(default='../static/imgs/promo.png', upload_to='store/blogposts/'),
        ),
    ]
