# Generated by Django 4.2 on 2024-08-20 12:48

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/blogposts'),
        ),
        migrations.AlterField(
            model_name='homeimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/home_images'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/promotions'),
        ),
    ]
