# Generated by Django 4.2 on 2024-08-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_contactmail_homeimages_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('catch_phrase', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='base/home_image')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeImages',
        ),
        migrations.RenameField(
            model_name='contactmail',
            old_name='content',
            new_name='message',
        ),
    ]
