from django.urls import path, register_converter
from .views import *
from utils import HashIdConverter

register_converter(HashIdConverter, "hashid")

urlpatterns = [
    path('', home, name='home'),
    path('promotions/', promotions, name='promotions'),
    path('promotions/<hashid:pk>/', promo_details, name='promo_details'),
    # ----------------------- blogposts ------------------------------
    path('blogposts/', blog, name='blog'),
    path('blogposts/add/', add_blogpost, name='add_blogpost'),
    path('blogposts/<hashid:pk>/', blogpost, name='blogpost'),
    path('blogposts/<hashid:pk>/info/', blogpost_info, name='blogpost_info'),
    path('blogposts/<hashid:pk>/edit/', edit_blogpost, name='edit_blogpost'),
    path('blogposts/<hashid:pk>/like/', like_blogpost, name='like_blogpost'),
    path('blogposts/<hashid:pk>/create/comment/', create_blog_comment, name='create_blog_comment'),
    path('blogposts/<hashid:pk>/edit/comment/', edit_blog_comment, name='edit_blog_comment'),
    # ----------------------- newsletter ------------------------------
    path('mailing_list/', mailing_list, name='mailing_list'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    # ----------------------- extras ------------------------------
    path('terms_of_use/', terms_of_use, name='terms_of_use'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    path('privacy_policy/', privacy_policy, name='privacy_policy'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    path('return_policy/', return_policy, name='return_policy'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    path('delivery_policy/', delivery_policy, name='delivery_policy'),
    path('feedbacks/', feedbacks, name='feedbacks'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    # --------------------------
    path('base/objects/<hashid:pk>/<str:model_name>/delete/',
         delete_base_object, name='delete_base_object'),
]
