from django.urls import path, register_converter
from .views import *
from utils import HashIdConverter

register_converter(HashIdConverter, "hashid")

urlpatterns = [
    path('', home, name='home'),
    path('promotions/', promotions, name='promotions'),
    path('promotions/list/', promo_list, name='promo_list'),
    path('promotions/<hashid:pk>/', promo_details, name='promo_details'),
    # ----------------------- blogposts ------------------------------
    path('blogposts/', blog, name='blog'),
    path('blogposts/<hashid:pk>/', blogpost, name='blogpost'),
    # path('blogposts/list/', blogposts_list, name='blogposts_list'),
    # path('blogposts/grid/', blogposts_grid, name='blogposts_grid'),
    # path('blogposts/filter/', filter_blogposts, name='filter_blogposts'),
    # path('blogposts/<hashid:pk>/like', like_blogpost, name='like_blogpost'),
    # path('blogposts/<hashid:pk>/dislike', dislike_blogpost, name='dislike_blogpost'),
    # path('blogposts/<hashid:pk>/comment', comment_blogpost, name='comment_blogpost'),
    # ----------------------- newsletter ------------------------------
    path('mailing_list/', mailing_list, name='mailing_list'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    # ----------------------- extras ------------------------------
    path('terms_of_use/', terms_of_use, name='terms_of_use'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    path('privacy_policy/', privacy_policy, name='privacy_policy'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    path('return_policy/', return_policy, name='return_policy'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    path('delivery_policy/', delivery_policy, name='delivery_policy'),
    path('feedbacks/', feedbacks, name='feedbacks'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]
