from django.urls import path, register_converter
from .views import *
from utils import HashIdConverter

register_converter(HashIdConverter, "hashid")

urlpatterns = [
    path('', home, name='home'),
    path('promotions/', promotions, name='promotions'),
    path('promotions/<hashid:pk>/', promo_details, name='promo_details'),
    # ----------------------- blogposts ------------------------------
    path('blogposts/', blog, name='blog'),
    path('blogposts/<hashid:pk>/', blogpost, name='blogpost'),
    path('blogposts/<hashid:pk>/info/', blogpost_info, name='blogpost_info'),
    path('blogposts/<hashid:pk>/like/', like_blogpost, name='like_blogpost'),
    path('blogposts/<hashid:pk>/create/comment/', create_blog_comment, name='create_blog_comment'),
    path('blogposts/<hashid:pk>/edit/comment/', edit_blog_comment, name='edit_blog_comment'),
    # ----------------------- newsletter ------------------------------
    path('mailing_list/', mailing_list, name='mailing_list'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    path('join_newsletter/', join_newsletter, name='join_newsletter'),
    # ----------------------- extras ------------------------------
    path('faq/', faq, name='faq'),
    path('ccm/', ccm, name='ccm'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('support/', support, name='support'),
    path('feedbacks/', feedbacks, name='feedbacks'),
    path('products/create/feedback/', create_feedback,
         name='create_feedback'),
    path('products/<hashid:pk>/edit/feedback/',
         edit_feedback, name='edit_feedback'),
    path('sale_policy/', sale_policy, name='sale_policy'),
    path('cstm_service/', cstm_service, name='cstm_service'),
    path('terms_of_use/', terms_of_use, name='terms_of_use'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    path('accessibility/', accessibility, name='accessibility'),
    path('return_policy/', return_policy, name='return_policy'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    path('privacy_policy/', privacy_policy, name='privacy_policy'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    path('delivery_policy/', delivery_policy, name='delivery_policy'),
    # --------------------------
    path('base/objects/<hashid:pk>/<str:model_name>/delete/',
         delete_base_object, name='delete_base_object'),
]
